name: belkis
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: 1.1.6
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  image_picker: ^1.0.4
  dots_indicator: ^3.0.0
  get_storage: ^2.1.1
  flutter_iconly: ^1.0.2
  getwidget: ^4.0.0
  cached_network_image: ^3.3.0
  youtube_player_flutter: ^8.1.2
  flutterfire_ui: ^0.4.3+20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Semi-Bold
      fonts:
        - asset: assets/fonts/AkayaTelivigala-Regular.ttf

    - family: Brand-Bold
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/WorkSans-SemiBold.ttf
